#!/usr/bin/env python3
"""Build docs/KNOBS.md and docs/knobs.json from captures/tweak_map.jsonl.

Usage: knobs_report.py [tweak_map.jsonl]
Model names come from docs/MODELS.md's tables (parsed back out of it).
"""
import collections
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..", "..")
src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "captures", "tweak_map.jsonl")
rows = [json.loads(l) for l in open(src)]

# model tables from MODELS.md: "## <title>" then "| id (`xx`) | name | ... |"
tables, cur = {}, None
for line in open(os.path.join(ROOT, "docs", "MODELS.md")):
    if line.startswith("## "):
        cur = tables.setdefault(line[3:].strip(), [])
    elif cur is not None and re.match(r"\| \d+ \(`", line):
        cur.append(line.split("|")[2].strip())
TABLE_TITLES = {0x00: "type 00 stomp (dynamics)", 0x02: "type 02 delay", 0x03: "type 03 mod",
                0x04: "type 04 reverb", 0x05: "type 05 stomp (distortion)", 0x06: "type 06 wah",
                0x07: "type 07 volume", 0x0A: "type 0A stomp (filter/synth)", 0x0C: "type 0C EQ"}
MISC_0B = {0: "Noise Gate", 1: "Compressor", 2: "Room (CAB/ER)", 10: "FX Loop", 12: "Variax"}


def model_name(cat, table, model):
    if cat == 0:
        lst = tables.get("amp (category 00)", []) if table == 2 else []
    elif table == 0x0B:
        return MISC_0B.get(model, "?")
    else:
        lst = tables.get(TABLE_TITLES.get(table, ""), [])
    return lst[model] if model < len(lst) else "?"


def clean(k):
    k = re.sub(r"[^A-Za-z0-9 /+&.-]", "", k).strip()
    k = re.sub(r"\s+\S$", "", k)          # OCR junk: "Send j", "Return ."
    return re.sub(r"\s+", " ", k)


votes = collections.defaultdict(collections.Counter)
patches = collections.defaultdict(set)
for x in rows:
    key = (x["category"], x["table"], x["model"])
    votes[(key, x["param"])][clean(x["knob"])] += 1
    patches[key].add(x["patch"])
models, conflicts = collections.defaultdict(dict), []
for (key, p), c in votes.items():
    top, n = c.most_common(1)[0]
    models[key][p] = (top, n, sum(c.values()))
    if len({re.sub("[^a-z]", "", k.lower()) for k in c}) > 1:
        conflicts.append((key, p, dict(c)))

out = ["# Knob names by model", "",
       "Generated by `tools/vm-capture/knobs_report.py` from a `tweak_sweep.py` run",
       "over all 64 patches on the unit (2026-09-24). For each patch, Gearbox's",
       "Tweak 1/2 menus give the knob names (OCR) and the parameter ID each one",
       "selects, and the patch load says which model is in each block. Parameter",
       "IDs are GearBox's 32-bit IDs (the dump record's `<idx><namespace>` read",
       "as a little-endian u32, see `L6T.md`).", "",
       "The Tweak menu only lists knobs Gearbox allows as tweak targets, so a model",
       "can have parameters missing here (compare `tools/l6t/preset_models.json`).",
       "**seen** = menu entries that agreed on the name / total entries for that",
       "parameter. Models that appear in only one patch rest on a single OCR'd",
       "menu and should be treated as less certain.", ""]
if conflicts:
    out += ["**Name conflicts** (the same model and parameter read differently in",
            "different patches): " + "; ".join(
                f"`{k[0]:02x}/{k[1]:02x}/{k[2]}` {p}: {c}" for k, p, c in conflicts), ""]
CAT = {0: "amp", 1: "cab", 2: "effect"}
for key in sorted(models):
    cat, table, model = key
    ps = sorted(patches[key], key=lambda s: (int(s[:-1]), s[-1]))
    out += [f"## {CAT.get(cat, cat)} table `{table:02X}` model {model}: {model_name(*key)}", "",
            f"Seen in {len(ps)} patch(es): {', '.join(ps)}", "",
            "| Param ID | Knob | seen |", "|---|---|---|"]
    for p, (k, n, tot) in sorted(models[key].items()):
        out.append(f"| `{p.upper()}` | {k} | {n}/{tot} |")
    out.append("")
open(os.path.join(ROOT, "docs", "KNOBS.md"), "w").write("\n".join(out))
json.dump({f"{c:02x}/{t:02x}/{m}": {"name": model_name(c, t, m),
                                    "params": {p: v[0] for p, v in ps.items()}}
           for (c, t, m), ps in models.items()},
          open(os.path.join(ROOT, "docs", "knobs.json"), "w"), indent=1, sort_keys=True)
print(f"{len(models)} models, {len(conflicts)} conflicts")
